### ISSUE TITLE
UICFacility - FacilityID Re-calculation

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#13]
If I try to change the CountyFIPS, the FacilityId is not recalculated to include that new CountyFIPs in the calculated value.  This may not actually be a problem since the County is automatically chosen.  However, the editors will need to be warned about this.

**Comment by steveoh** [comment]
Maybe county fips should be read only so people cannot edit it? I don't really like that idea because the tool might not always be right. We could also recalculate the id.

I also did ask you about this one before...

> how often do facilities move? like how the id is created from the fips code, does that ever change later in the game?

Your answer

> Regarding the FaciltiyID that should never change since it is based on the countyFIPS

I thought this might have been from this rule bug but I do not think it is...

https://github.com/agrc/uic-attribute-rules/blob/e2008ec367b175e69e0b46a3a09e436329b88f27/src/rules/well.py#L47

**Comment by CanDKD** [comment]
90% of the time this will never be a problem.  I can't imagine an instance where an editor would want to change the County.  However, a problem arises if a facility polygon crosses a county boundary, the facility polygon is enlarged such that greater than 50% of the polygon area then lies in a county different from that assigned in the initial record.  The FacilityID is not re-calculated.  I apologized for not anticipating the 0.5% instances which may cause problems.
